version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./_docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/laravel
    depends_on:
      - php
      - mysql

  php:
    build:
      context: _docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./backend:/var/www/laravel

  mysql:
    image: "mysql:8.0"
    ports:
      - "3316:3306"
    env_file:
      - _docker/env/mysql.env
    volumes:
      - db_dats:/var/lib/mysql

  composer:
    build:
      context: _docker/dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./backend:/var/www/laravel

  artisan:
    build:
      context: _docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./backend:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

  node:
    build:
      context: _docker/dockerfiles
      dockerfile: node.Dockerfile
    ports:
      - "4000:5173"
    volumes:
      - ./frontend:/var/www/app
    command: npm run dev -- --host



volumes:
  db_dats:




